List<String> stationList = [
  'Ancol',
  'Angke',
  'Batu Ceper',
  'Bekasi',
  'Bekasi Timur',
  'Bogor',
  'Bojong Gede',
  'Bojong Indah',
  'Buaran',
  'Cakung',
  'Catang',
  'Cawang',
  'Cibinong',
  'Cibitung',
  'Cicayur',
  'Cikarang',
  'Cikeusal',
  'Cikini',
  'Cikoya',
  'Cilebut',
  'Cilegon',
  'Cilejit',
  'Cisauk',
  'Citayam',
  'Citeras',
  'Daru',
  'Depok',
  'Depok Baru',
  'Duren Kalibata',
  'Duri',
  'Gambir',
  'Gang Sentiong',
  'Gondangdia',
  'Grogol',
  'Jakarta Kota',
  'Jambubaru',
  'Jatinegara',
  'Jayakarta',
  'Juanda',
  'Jurang Mangu',
  'Kali Deres',
  'Kampung Bandan',
  'Karangantu',
  'Karet',
  'Kebayoran',
  'Kemayoran',
  'Klender',
  'Klender Baru',
  'Kramat',
  'Kranji',
  'Krenceng',
  'Lenteng Agung',
  'Maja',
  'Mangga Besar',
  'Manggarai',
  'Matraman',
  'Merak',
  'Metland Telaga Murni',
  'Nambo',
  'Palmerah',
  'Parung Panjang',
  'Pasar Minggu',
  'Pasar Minggu Baru',
  'Pasar Senen',
  'Pesing',
  'Pondok Cina',
  'Pondok Jati',
  'Pondok Ranji',
  'Poris',
  'Rajawali',
  'Rangkasbitung',
  'Rawa Buaya',
  'Rawa Buaya',
  'Rawa Buntu',
  'Sawah Besar',
  'Serang',
  'Serpong',
  'Sudimara',
  'Sudirman',
  'Sudirman',
  'Taman Kota',
  'Tambun',
  'Tanah Abang',
  'Tanah Tinggi',
  'Tangerang',
  'Tanjung Barat',
  'Tanjung Priuk',
  'Tebet',
  'Tenjo',
  'Tigaraksa',
  'Tonjongbaru',
  'Universitas Indonesia',
  'Universitas Pancasila',
  'Walantaka'
];